spring:
  datasource:
    url: jdbc:mariadb://localhost:13306/liveklass
    username: liveklass
    password: liveklass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 16379
